name: sustainable_world
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
 
  hooks_riverpod: ^2.3.6
  flutter_hooks: any 
  freezed_annotation: ^2.4.1
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  
  flutter_chips_input: ^2.0.0
  flutter_map: ^5.0.0
  flutter_native_splash: ^2.3.1
  flutter_scale_tap: ^1.0.5
  flutter_slider_indicator: ^1.0.0
  font_awesome_flutter: ^10.5.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  google_fonts: ^5.1.0
  http: ^1.1.0
  image_picker: ^0.8.4+4
  intl: any
  json_annotation: ^4.4.0
  latlong2: ^0.9.0
  line_icons: ^2.0.1
  location: ^4.3.0
  pattern_formatter: ^3.0.0
  photo_view: ^0.14.0
  reorderable_grid_view: ^2.2.2
  share_plus: ^4.0.3
  smooth_page_indicator: ^1.0.0+2
  syncfusion_flutter_charts: ^20.2.36
  tuple: ^2.0.0
  url_launcher: ^6.0.20
  validated: ^2.0.0
  dio: ^5.3.0
  loading_overlay: ^0.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.9
  jwt_decoder: ^2.0.1
  flutter_tags: any
  uuid: ^3.0.6
  confetti: ^0.7.0
  flutter_launcher_icons: ^0.13.1
  flutter_otp_text_field: ^1.1.1
  
  
  permission_handler: ^10.2.0
  amplify_flutter: ^1.3.0
  amplify_core: ^1.3.0
 
  amplify_api: ^1.3.0
  amplify_auth_cognito: ^1.3.0
  amplify_datastore: ^1.3.0
  amplify_storage_s3: ^1.3.0
  flutter_stripe: ^9.3.0
  flutter_dotenv: ^5.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  hive_generator: ^2.0.0
 


 
 

  



flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  remove_alpha_ios: true

flutter_app_name:
  name: "Sustainable World"

flutter_native_splash:
  color: "#008080"
  image: "assets/images/splash.png"
  android_gravity: fill
  android: true
  android12: true
  ios: true
  ios_content_mode: center
  web: false
